### ISSUE TITLE
tensorflow-io 0.15.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1060]
With TensorFlow 2.3 final release, we can consider having a v0.15.0 release for 2.3, as was mentioned in #1023

Here is the list of items for 0.15.0:

- [x] Bump TF version to 2.3.0 final (PR #1058)
- [x] Merge PRs with low risk (no behavior changes) if time permit (PR #1034, #1055, #1057)
- [x] Update RELEASE.md/README.md to capture 0.15.0 changes (PR #1062)
- [x] When GitHub Actions complete the build against the master, download the artifact with the name `tensorflow-io-release`. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x] Push all binaries to PyPI.org.

And follow up after 0.15.0 release:

- [x] Update docs/tutorials/colorspace.ipynb to use `pip install tensorflow-io` (instead of `tensorflow-io-nightly`).
- [x] Push to tensorflow.org/io (with the help from docs team).

/cc @vlasenkoalexey @terrytangyuan @BryanCutler  @dmitrievanthony

**Comment by kvignesh1420** [comment]
@yongtang , to address point 5, the example in our README.md works fine

```
In [1]: import tensorflow as tf
   ...: import tensorflow_io as tfio
   ...:
   ...: # Read MNIST into Dataset
   ...: d_train = tfio.IODataset.from_mnist(
   ...:     'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz',
   ...:     'http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz').batch(1)
   ...:
   ...: # By default image data is uint8 so convert to float32.
   ...: d_train = d_train.map(lambda x, y: (tf.image.convert_image_dtype(x, tf.float32), y))
   ...:
   ...: model = tf.keras.models.Sequential([
   ...:   tf.keras.layers.Flatten(input_shape=(28, 28)),
   ...:   tf.keras.layers.Dense(512, activation=tf.nn.relu),
   ...:   tf.keras.layers.Dropout(0.2),
   ...:   tf.keras.layers.Dense(10, activation=tf.nn.softmax)
   ...: ])
   ...: model.compile(optimizer='adam',
   ...:               loss='sparse_categorical_crossentropy',
   ...:               metrics=['accuracy'])
   ...:
   ...: model.fit(d_train, epochs=5, steps_per_epoch=10000)

2020-07-29 20:12:54.897660: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2020-07-29 20:12:55.046517: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-29 20:12:55.068496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb676ec8470 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-29 20:12:55.068515: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Epoch 1/5
10000/10000 [==============================] - 19s 2ms/step - loss: 0.3902 - accuracy: 0.8842
Epoch 2/5
10000/10000 [==============================] - 19s 2ms/step - loss: 0.2571 - accuracy: 0.9281
Epoch 3/5
10000/10000 [==============================] - 19s 2ms/step - loss: 0.2351 - accuracy: 0.9404
Epoch 4/5
10000/10000 [==============================] - 20s 2ms/step - loss: 0.2234 - accuracy: 0.9423
Epoch 5/5
10000/10000 [==============================] - 19s 2ms/step - loss: 0.2381 - accuracy: 0.9414
Out[1]: <tensorflow.python.keras.callbacks.History at 0x154b49d90>
```

If we are we looking at some other sanity tests, please let me know.

**Comment by yongtang** [comment]
Thanks @kvignesh1420 ! We normally do the final sanity immediately before pushing the binary to PyPI.org. I will keep you posted. Greatly appreciate your help!

**Comment by yongtang** [comment]
The candidate wheel files are downloadable from https://github.com/tensorflow/io/actions/runs/190365823 with artifact name `tensorflow-io-release`, below are the sha256s:
```
$ sha256sum *.whl
3f5d6db637f612c86f509371c428fff3b4a6de7bd41abb25e8ecc3c729f7471a  tensorflow_io-0.15.0-cp35-cp35m-macosx_10_13_x86_64.whl
2532de89b901698385e325c77c65e2a088d923c8ea60020b1cc0753556dddcb8  tensorflow_io-0.15.0-cp35-cp35m-manylinux2010_x86_64.whl
9ce35fdd093e8a89d3cc4ff4c289d14ac07580594e9df02b4a250db2003f95d9  tensorflow_io-0.15.0-cp35-cp35m-win_amd64.whl
53491487c34c148f30feefb5d5146ad373c6d3165559073437c036de8c9227bc  tensorflow_io-0.15.0-cp36-cp36m-macosx_10_13_x86_64.whl
0f20333fd8dbc0b087df2590ca63cadd1a25d75d892715ce0a5a7febfdd7a85b  tensorflow_io-0.15.0-cp36-cp36m-manylinux2010_x86_64.whl
461337dfcb4d6c5583f4917933b47ea40e473d8bdee78793bf41b4cb11759bc5  tensorflow_io-0.15.0-cp36-cp36m-win_amd64.whl
d46fa8cf01757fb5f742ca4ab623eb8bb74a8083629a1b01a868a835a17ef35f  tensorflow_io-0.15.0-cp37-cp37m-macosx_10_13_x86_64.whl
13411a3e4255b70b1f76e11455f4970bc43d1ba930228344c46b32736193abcb  tensorflow_io-0.15.0-cp37-cp37m-manylinux2010_x86_64.whl
74e36061030da1e2c04c7962e4a2c7c8ae7ee10ceeca2e158199200056004042  tensorflow_io-0.15.0-cp37-cp37m-win_amd64.whl
e0f209a12a5e320618293467e51a2d9c49291402ebbd80dd409fc322f0a0c9f5  tensorflow_io-0.15.0-cp38-cp38-macosx_10_13_x86_64.whl
d5210b62f3f06fca922a2eb44437919c930cfaf66801d94f94ace8f34f48b839  tensorflow_io-0.15.0-cp38-cp38-manylinux2010_x86_64.whl
d6087ecadd605243b6346ac7c3503818b43917a2bf48fc7676ffc2ca5543f8db  tensorflow_io-0.15.0-cp38-cp38-win_amd64.whl
```

**Comment by yongtang** [comment]
Will push to PyPI.org shortly.

**Comment by yongtang** [comment]
Pip Wheels pushed to https://pypi.org/project/tensorflow-io/0.15.0/
Release available in https://github.com/tensorflow/io/releases/tag/v0.15.0

**Comment by yongtang** [comment]
New docs and tutorials have been pushed as well: https://www.tensorflow.org/io/tutorials/colorspace

Thanks all for the contributions! 👍 🎉 🎆
