### ISSUE TITLE
tensorflow-io 0.16.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1156]
With TensorFlow 2.4 release candidate out soon (this week or next), we can consider having a v0.16.0 release for 2.3, as was discussed in our last meeting.

Here is the list of items for 0.16.0:

- [x] Bump tensorflow-io version to 0.16.0 (PR #1157)
- [x] Update RELEASE.md to capture 0.16.0 changes (PR #1157)
- [x] Update README.md to update 0.16.0 release date (PR #1159)
- [x] When GitHub Actions complete the build against the master, download the artifact with the name tensorflow-io-release. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x]  Push all binaries to PyPI.org.
- [x] Address the points related to docker releases in https://github.com/tensorflow/io/pull/1153#issuecomment-713163786
- [x] Add an overview description to our [docker releases](https://hub.docker.com/r/tfsigio/tfio).  Currently, it is blank.

And follow up immediately after 0.16.0 release:
- [x] Update docs/tutorials/colorspace.ipynb to use pip install tensorflow-io (instead of tensorflow-io-nightly). (PR: https://github.com/tensorflow/io/pull/1160)
- [x] Update docs/tutorials/kafka.ipynb to use pip install tensorflow-io (instead of tensorflow-io-nightly). (PR: https://github.com/tensorflow/io/pull/1160)
- [x] Update docs/tutorials/elasticsearch.ipynb to use pip install tensorflow-io (instead of tensorflow-io-nightly). (PR: https://github.com/tensorflow/io/pull/1160)
- [x] Push to tensorflow.org/io (with the help from docs team).

Finally, post 0.16.0 release:
- [x] Bump TF version to 2.4.0 (rc) (PR #1143)
- [x] Resolve any issues in #1143 to use modular file systems C API (as discussed in our last meeting). (PR #1143)
        Note since tensorflow/tensorflow#43680 has been merged, we are finally unblocked.
- [x] Send email to SIG IO

/cc @vlasenkoalexey @terrytangyuan @kvignesh1420 @BryanCutler @dmitrievanthony

**Comment by yongtang** [comment]
@kvignesh1420 Do you have a PyPI.org account? If you do I can add you to the maintainer of tensorflow-io repo https://pypi.org/project/tensorflow-io/ if you prefer.

**Comment by kvignesh1420** [comment]
@yongtang my PyPI handle is https://pypi.org/user/kvignesh1420/.

Also, I have added a few points to the task list above. (related to docker releases and updates to notebooks)

**Comment by yongtang** [comment]
@kvignesh1420 Thanks! Invite for PyPI.org has been sent out.

**Comment by kvignesh1420** [comment]
@terrytangyuan if time permits, can this issue https://github.com/tensorflow/io/issues/1142 be addressed before the release? We can build and add the `r-latest` tag to this image.

**Comment by terrytangyuan** [comment]
Looks like we are already releasing so I don't think we will have enough time.

**Comment by kvignesh1420** [comment]
@yongtang here is a draft of the `overview content` in docker hub.

## TensorFlow-IO Docker Images

TensorFlow I/O is a collection of Dataset, streaming, and file system extensions maintained by TensorFlow SIG-IO that extend TensorFlow's built-in support for io related operations.

The dockerfiles are available on [Github](https://github.com/tensorflow/io/tree/master/tools/docker) along with the readily available [tags](https://hub.docker.com/r/tfsigio/tfio/tags).

## Base Image Tags

- `0.xx.0`, `latest`, and `nightly` tags come with TensorFlow-IO pre-installed. Versioned tags contain their version, the `latest` tags contain the latest release and the `nightly` images come with the TensorFlo-IO nightly Python package. Additionally, since Tensorflow-IO is dependent on Tensorflow, the images come with the [compatible Tensorflow version](https://github.com/tensorflow/io#tensorflow-version-compatibility).

- `-devel` images are based on Tensorflow's `custom-op` images and come with Bazel. These are ideal for exploring and developing changes to TensorFlow-IO.

## Running Containers

Start the container with the latest release of the package.

```console
$ docker run -it --rm tfsigio/tfio bash
```

Start the development container and mount the ${PWD} to explore and build with the ops.

```console
$ docker run -it --rm --name tfio-dev --net=host -v ${PWD}:/v -w /v tfsigio/tfio:latest-devel bash
```
Please check the docs for [development using docker](https://github.com/tensorflow/io#docker).

cc: @terrytangyuan @BryanCutler @vlasenkoalexey

**Comment by yongtang** [comment]
Thanks @kvignesh1420 👍 ! The README page of the docker hub has been updated.

**Comment by yongtang** [comment]
I tested manually with release binary candidates and sanity looks fine.

**Comment by yongtang** [comment]
Below are the release binary candidates:
```
0f558f6f8add7c061a7359e49fa7fd16c3b20fe19b432e0b5dcdcf1b097fad75  tensorflow_io-0.16.0-cp36-cp36m-macosx_10_13_x86_64.whl
f3878516cfa9d7eb69dd4039ef6565e6d5912782ddbcc1e027064c85d493b516  tensorflow_io-0.16.0-cp36-cp36m-manylinux2010_x86_64.whl
f3c1088ea03dd1beb4ada99aa9319801dae32e01bdfd599a14e0a47a2d04c75c  tensorflow_io-0.16.0-cp36-cp36m-win_amd64.whl
4b613a4129667b85b8cf09481e95babe15b7f597d8162c6614c359174f1aed44  tensorflow_io-0.16.0-cp37-cp37m-macosx_10_13_x86_64.whl
638174fcd38a8c18090c67be0c47b060c95cbdeabf9e9823566f8805717d6acc  tensorflow_io-0.16.0-cp37-cp37m-manylinux2010_x86_64.whl
32b77ff85ceec5c6390d500dfaae41ef55c28b6497eeaf4ee3a9e84249fa0035  tensorflow_io-0.16.0-cp37-cp37m-win_amd64.whl
ba39848f61dfdaffaf8df35814d339316bcb8272d2fa6aff8552c4e9c8c4c278  tensorflow_io-0.16.0-cp38-cp38-macosx_10_13_x86_64.whl
29a343c7921f4a9d880ae7ad5b200c4dda2e1affc857e8e05087383f18a41eb2  tensorflow_io-0.16.0-cp38-cp38-manylinux2010_x86_64.whl
427b099eb17f70872c0f7dbe81360b88a93b93d57e1c3135dbbff682f5ae2f46  tensorflow_io-0.16.0-cp38-cp38-win_amd64.whl
```

**Comment by yongtang** [comment]
The release of 0.16.0 is available:

https://pypi.org/project/tensorflow-io/0.16.0/#files

https://github.com/tensorflow/io/releases/tag/v0.16.0

**Comment by kvignesh1420** [comment]
@MarkDaoust @lamberta  can we update the docs in the website as the PR https://github.com/tensorflow/io/pull/1160 has been merged?

**Comment by yongtang** [comment]
PR #1143 will cover most of the post 0.16.0 items. I think we haven't send out email to SIG IO list yet. Will send out shortly.

**Comment by MarkDaoust** [comment]
Okay, I tried running the updates on Oct 27th, and most of them went fine. 

I hit two errors:

1. in kafka.ipynb

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-6c9791c78bae> in <module>
      8   mini_ds = mini_ds.map(decode_kafka_online_item)
      9   mini_ds = mini_ds.batch(BATCH_SIZE)
---> 10   model.fit(mini_ds, epochs=3)

/tmpfs/src/tf_docs_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/tmpfs/src/tf_docs_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1102               end_step = step + data_handler.step_increment
   1103               callbacks.on_train_batch_end(end_step, logs)
-> 1104         epoch_logs = copy.copy(logs)
   1105 
   1106         # Run validation.

UnboundLocalError: local variable 'logs' referenced before assignment
UnboundLocalError: local variable 'logs' referenced before assignment
```

2.  elasticsearch.ipynb, 


```
---------------------------------------------------------------------------
SubprocessError                           Traceback (most recent call last)
<ipython-input-1-5ccb0daac3e4> in <module>
      1 es_server = Popen(['elasticsearch-7.9.2/bin/elasticsearch'], 
      2                   stdout=PIPE, stderr=STDOUT,
----> 3                   preexec_fn=lambda: os.setuid(1))
      4 
      5 # Sleep for few seconds to let the instance start.

/usr/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1363                             err_msg += ': ' + repr(err_filename)
   1364                     raise child_exception_type(errno_num, err_msg, err_filename)
-> 1365                 raise child_exception_type(err_msg)
   1366 
   1367 

SubprocessError: Exception occurred in preexec_fn.
SubprocessError: Exception occurred in preexec_fn.
```

If I'm reading this correctly... you're trying to switch to the `daemon` user, but [`os.setuid` only works if you're root](https://www.geeksforgeeks.org/python-os-getuid-and-os-setuid-method/).

Maybe you can do this with:

```
%%bash --bg
sudo -H -u daemon elasticsearch-7.9.2/bin/elasticsearch
```

**Comment by MarkDaoust** [comment]
Okay, 

For kafka, I don't think this is something we can fix, because it looks like this is in the keras library. But that error looks like it has been fixed in TF2.4.

For elasticsearch I get.  

`CalledProcessError: Command 'b'\ncurl -sX GET "localhost:9200/"\n'' returned non-zero exit status 7.`
and scrolling up through my logs I see a lot of:

```
changing ownership of 'elasticsearch-7.9.2/lib/elasticsearch-launchers-7.9.2.jar': Operation not permitted\nchown: changing ownership of 'elasticsearch-7.9.2/lib/jts-core-1.15.0.jar': Operation not permitted\nchown: changing ownership of 'elasticsearch-7.9.2/lib/elasticsearch-secure-sm-7.9.2.jar': Operation not permitted\nchown: changing ownership of 'elasticsearch-7.9.2/lib/snakeyaml-1.26.jar': Operation not permitted\nchown: changing ownership of 'elasticsearch-7.9.2/lib/lucene-join-8.6.2.jar':
```

Does anyone know how necessary this whole `daemon` setup is for that tutorial. Can we just run it of the current user and add a note saying that for a real setup you should probably use `daemon`.

It's hard to be sure that's the problem. I'll investigate a little more.

I also notice that the output of the audio tutorial has changed. Here:

```
# Convert to db scale mel-spectrogram
dbscale_mel_spectrogram = tfio.experimental.audio.dbscale(
    mel_spectrogram, top_db=80)
```

You'd need to set `top_db=40` to get images that look like [the current ones](https://tensorflow.org/io/tutorials/audio).

Is this behavior change a known bug or bugfix?

**Comment by yongtang** [comment]
Thanks @MarkDaoust , I think the dbscale was an issue (see #1035) that has been fixed in PR #1037. So they are expected.

**Comment by yongtang** [comment]
@MarkDaoust For elasticsearch will take a look. Also /cc @kvignesh1420

**Comment by kvignesh1420** [comment]
@MarkDaoust I see that, in a general colab notebook, the user is root by default and can change ownerships of dir's as required. Not sure if that's the case while building docs? Also, when I don't change the ownership of the directory to `daemon:daemon` and start the process as `daemon` user, I get the following error:

```console
[2020-11-04T07:13:12,374][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [b520dd7b2a91] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
```

**Comment by MarkDaoust** [comment]
I've published the updates for everything except elasticsearch.ipynb

@kvignesh1420, yes, in  the container that builds the site you're not root by default. So we need to find something that works on both. 

Switching that chmod to `sudo chmod` gets me a little farther, but now it's failing with:

```
FailedPreconditionError: Corrupted response from the server null
         [[{{node IO>ElasticsearchReadableNext}}]]
```

https://gist.github.com/MarkDaoust/bd7d027969b0d24b506e690a8d03b7a6

If you don't have any good ideas on how to fix this, the next option is just to save the output into the notebook, then the site-builder won't execute it.

**Comment by kvignesh1420** [comment]
@MarkDaoust I reduced the number of columns for building the feature layer as that cell was taking quite some time to execute. Please check https://github.com/tensorflow/io/pull/1172

**Comment by MarkDaoust** [comment]
That's published now: https://www.tensorflow.org/io/tutorials/elasticsearch

**Comment by kvignesh1420** [comment]
@MarkDaoust thanks for the help. Also, I see that the kafka.ipynb is not yet updated. Is it due to the keras issue?

**Comment by MarkDaoust** [comment]
> I see that the kafka.ipynb is not yet updated. Is it due to the keras issue?

Yes. I think this will be fixed in the 2.4 release.

**Comment by kvignesh1420** [comment]
@MarkDaoust please take a look at https://github.com/tensorflow/io/pull/1175.

**Comment by kvignesh1420** [comment]
@yongtang all the items have been completed other than the Kafka notebook update. We can take it up after tf2.4 release or after 0.17.0 release of tfio. Shall we close this now?

**Comment by yongtang** [comment]
@kvignesh1420 Let's close this issue. Given 2.4.0 is in rc4 already, I think 2.4.0 final will likely be released early next week. We can then work on 0.17.0.
