### ISSUE TITLE
tensorflow-io 0.17.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1228]
With TensorFlow 2.4 final release out now, we can working on a v0.17.0 release for TF 2.4, as was discussed in our meetings.

Here is the list of items for 0.17.0:

- [x] Bump tensorflow-io version to 0.17.0 (PR #1227)
- [x] Update RELEASE.md to capture 0.17.0 changes (PR #1227)
- [x] Update README.md to update 0.17.0 release date (PR #1227)
- [x] When GitHub Actions complete the build against the master, download the artifact with the name tensorflow-io-release. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x] Push all binaries to PyPI.org.
- [x] Release on GitHub repo with v0.17.0 tag.

And follow up after 0.17.0 release:
- [ ] Push to tensorflow.org/io (with the help from docs team).
- [ ] Send email to SIG IO

/cc @vlasenkoalexey @terrytangyuan @kvignesh1420 @BryanCutler @dmitrievanthony

**Comment by yongtang** [comment]
Tested the candidate binary on Linux with python 3.6, 3.7, and 3.8. All works fine:
```
0a18692a076995018d0e3951e5f2a1364978b1c86a2a8c9ae73ec4176a37a2a0  tensorflow_io-0.17.0-cp36-cp36m-macosx_10_13_x86_64.whl
33ff333eb2907d3de8d5c21f2dfee663b1f144d527ff2b195492a2a2d50619ca  tensorflow_io-0.17.0-cp36-cp36m-manylinux2010_x86_64.whl
e366d7a38871a52ea62ab3ec726531748ac3fc07c97502ecd4d16242477009c5  tensorflow_io-0.17.0-cp36-cp36m-win_amd64.whl
ef5364b57b42280c102bd37962648e4f2ceb858463f1ef9d59d3eee8181395e1  tensorflow_io-0.17.0-cp37-cp37m-macosx_10_13_x86_64.whl
94767c841d6fd5543a1f1b864d88deee510972443092f513aa558478cd13c363  tensorflow_io-0.17.0-cp37-cp37m-manylinux2010_x86_64.whl
f74c08b4277db2b1192a54dee2d020a9a3277f763bec81c15c0e24406948274d  tensorflow_io-0.17.0-cp37-cp37m-win_amd64.whl
2529c41e52d787d9c6e10d253e958a4f3556ad659bd9e178fae80a5eacee1f6b  tensorflow_io-0.17.0-cp38-cp38-macosx_10_13_x86_64.whl
3e498f6ecf5a0346ca64265ccca34d1db48eea00b14f3f686f944e985c06bfdb  tensorflow_io-0.17.0-cp38-cp38-manylinux2010_x86_64.whl
a1790d89c38f5c1f8173883eb15524ea7d80ee30fff94e4cb8d23a168c45d465  tensorflow_io-0.17.0-cp38-cp38-win_amd64.whl
```

**Comment by yongtang** [comment]
Files uploaded to PyPI.org:
https://pypi.org/project/tensorflow-io/0.17.0/#files

**Comment by yongtang** [comment]
Release Tag available:
https://github.com/tensorflow/io/releases/tag/v0.17.0
