### ISSUE TITLE
tensorflow-io 0.18.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1420]
With TensorFlow 2.5 final release out now, we can working on a v0.18.0 release for TF 2.5, as was discussed in our meetings.

Here is the list of items for 0.180:

- [x] Bump tensorflow-io dependency to TF 2.5 (PR #1418)
- [x] Rename tensorflow-io-plugin-gs to tensorflow-io-gcs-filesystem (PR #1419)
- [ ] remove the existing tensorflow-io-plugin-gs-nightly from pypi 
- [x] Update RELEASE.md to capture 0.18.0 changes (PR #1421)
- [x] Update README.md to update 0.18.0 release date (PR #1421)
- [x] When GitHub Actions complete the build against the master, download the artifact with the name tensorflow-io-release. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x] Ideally, push to https://test.pypi.org for additional sanity test as we will release 2 wheels.
- [x] Push all binaries to PyPI.org.
- [x] Release on GitHub repo with v0.18.0 tag.

And follow up after 0.18.0 release:
- [x] Tutorial update of tfio.audio.experimental => tfio.audio
- [ ] Push to tensorflow.org/io (with the help from docs team).
- [ ] Send email to SIG IO

/cc @vlasenkoalexey @terrytangyuan @kvignesh1420 @burgerkingeater @BryanCutler @dmitrievanthony

**Comment by yongtang** [comment]
Had a false start, meant to upload `tensorflow_io_gcs_filesystem_nightly` but actually upload `tensorflow_io_gcs_filesystem` instead 😢  That means `tensorflow_io_gcs_filesystem` 0.18.0 has already been occupied by commit dcb3c1e

**Comment by yongtang** [comment]
It looks like everything is fine. I think the solution is to label dcb3c1e as 0.18.0, and go ahead to release tensorflow-io 0.18.0 with commit dcb3c1e.

**Comment by yongtang** [comment]
SHA256:
```
% shasum -a 256 *.whl
24af67221e8e5e7638f1e353489b0abfda2a68eb4a10eede8e58ebcfbb700c94  tensorflow_io-0.18.0-cp36-cp36m-macosx_10_14_x86_64.whl
98b409458d63d7bcf020bc13544851fe95fcc05fc3bf6726cc021beba0f78a8c  tensorflow_io-0.18.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
636968153712b5b30b2f8755136a005d5023916f3145a58ce1f386e1383ab01e  tensorflow_io-0.18.0-cp36-cp36m-win_amd64.whl
10f5256bd4a197759591d981c4d0ce6c4452f74603b42f772bbe80eb457cd333  tensorflow_io-0.18.0-cp37-cp37m-macosx_10_14_x86_64.whl
e78c7cca5736e6bb3e57875276c8a82f011060660191bf288eef2464c55a6e97  tensorflow_io-0.18.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
79d78543b62d04dbc78a9ccf936802e65ce2d30f07d5f4d4ea1dab638845f490  tensorflow_io-0.18.0-cp37-cp37m-win_amd64.whl
d0c664246b1c50dfd7670018f5dcc1cf6c569c1d0873dd851707874cbface9fa  tensorflow_io-0.18.0-cp38-cp38-macosx_10_14_x86_64.whl
52c574160a1fdbef16dce727e1ddc0a1bfadebf538a5dc9ae922291facdddcff  tensorflow_io-0.18.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
ae9614936f91302390712b0a63391e5af6a2f606e14f47ef5ec96698ea85b1df  tensorflow_io-0.18.0-cp38-cp38-win_amd64.whl
b8bb6fffd5d722d0d2ad815817d81f1c299ebbffb370fb95e2ab968d2ba1cfaf  tensorflow_io-0.18.0-cp39-cp39-macosx_10_14_x86_64.whl
6e353da5e3837630e7f49abf05d1ca888fe93fe84eb78fef6dc7abbb3b949522  tensorflow_io-0.18.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
77e26aa160ae42c1b149f9bcb543034d43bc119f0ce65936c54ed09ac9a4aa87  tensorflow_io-0.18.0-cp39-cp39-win_amd64.whl
04b059474289743c105050a6eafbb958121140e0f26c088aefed553e9e803817  tensorflow_io_gcs_filesystem-0.18.0-cp36-cp36m-macosx_10_14_x86_64.whl
e6ca48b33a77abb67307b7e3673eb6bec93185ef0c47c3ee6304026c598dfde0  tensorflow_io_gcs_filesystem-0.18.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
81410b0ef5442e3f4890a7c925e0da9b587a8dd7a04cf7c0b28595d804254fa2  tensorflow_io_gcs_filesystem-0.18.0-cp36-cp36m-win_amd64.whl
41403032e3e938992c1591deb305e602fa0c9573e8ad6a578b804e5d59a09676  tensorflow_io_gcs_filesystem-0.18.0-cp37-cp37m-macosx_10_14_x86_64.whl
3a75210527b0bd0482994325e8832c07d6333d7b76a2bc0cb7a3daaf103436f1  tensorflow_io_gcs_filesystem-0.18.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
a95629e38e0416cb620b7d50de37451535e0e1a0779a8e6608cfabad9e4f6a1c  tensorflow_io_gcs_filesystem-0.18.0-cp37-cp37m-win_amd64.whl
280820f19c5c66a20e0122b9430bb54aeea91bd65d46edd3121927e5e8c24341  tensorflow_io_gcs_filesystem-0.18.0-cp38-cp38-macosx_10_14_x86_64.whl
de39256fc7aad3aa7d0333a3d86f476d76de99070544860bd744b1af65264b39  tensorflow_io_gcs_filesystem-0.18.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
4cc0d41c91ec209b8b7f84b3d15f8a39f2d8acbd6148203d7b27e9835ede0a7a  tensorflow_io_gcs_filesystem-0.18.0-cp38-cp38-win_amd64.whl
561ad54ce5800c605dbf8d43262f18e1e17a016d78d3734a0609ac6dbb3fefff  tensorflow_io_gcs_filesystem-0.18.0-cp39-cp39-macosx_10_14_x86_64.whl
502e39b1a4f8f6d0a4a297957aca9f5b8812d9be4c99ad26a1efec5d8e7491b9  tensorflow_io_gcs_filesystem-0.18.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
02585355cfeff116131f3244002351df12582c22f9352c966a7de2f069c9a047  tensorflow_io_gcs_filesystem-0.18.0-cp39-cp39-win_amd64.whl
```

**Comment by yongtang** [comment]
Will just go ahead and push the rest `tensorflow_io-0.18.0-*.whl` files to pypi.org, as we want to make sure the `tensorflow_io-0.18.0-*.whl`  and `tensorflow_io_gcs_filesystem-0.18.0-*.whl` matches the same commit. Then will label v0.18.0 release. Will create a PR to update README.md and RELEASE.md after that.

**Comment by yongtang** [comment]
v0.18.0 is labeled in https://github.com/tensorflow/io/releases/tag/v0.18.0

**Comment by yongtang** [comment]
PR #1421 has been opened to update README.md and RELEASE.md.

**Comment by kvignesh1420** [comment]
Thanks @yongtang

**Comment by kvignesh1420** [comment]
As https://github.com/tensorflow/io/pull/1437 has been merged, @tensorflow/docs-team can we push the docs to tensorflow.org/io? cc: @yongtang

**Comment by yongtang** [comment]
Close as we are moving to 0.19.0.
