### ISSUE TITLE
tensorflow-io 0.19.0 release 

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1461]
With TensorFlow 2.6.0 branch cut really soon, we can working on a v0.19.0 release before TF 2.6.0, as was discussed in our meetings. (We will release 0.20.0 when TF 2.6.0 final is out):

Here is the list of items for 0.19.0:

- [x] Bump tensorflow-io version number to 0.19.0 (PR #1462)
- [x] Update RELEASE.md to capture 0.19.0 changes (PR #1462)
- [x] Update README.md to update 0.19.0 release date (PR #1462)
- [x] When GitHub Actions complete the build against the master, download the artifact with the name tensorflow-io-release. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x] Ideally, push to https://test.pypi.org for additional sanity test.
- [x] Push all binaries to PyPI.org.
- [x] Release on GitHub repo with v0.19.0 tag.

And follow up after 0.19.0 release:
- [ ] Send email to SIG IO

/cc @vlasenkoalexey @terrytangyuan @kvignesh1420 @burgerkingeater @BryanCutler @dmitrievanthony

**Comment by kvignesh1420** [comment]
@yongtang thanks for creating the actions items. However, can we close the `0.18.0` release related tasks here: https://github.com/tensorflow/io/issues/1420 ?

**Comment by yongtang** [comment]
Did the sanity tests with Linux 3.6/3.7/3.8/3.9 and all looks ok. Binaries are:
```
a9a111e42cef1976087cbdf7bf3273dbf73875c8064d97bc144fc12317ce2e0a  tensorflow_io-0.19.0-cp36-cp36m-macosx_10_14_x86_64.whl
37ebf6ea388f0fb209d9fde11cdf0513c183ff4e6222b7d069d3bc58471d10f7  tensorflow_io-0.19.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
2b35565bdaf4c10a913383d899b267cb4d24c3f88f6dcf0c8ce9a0bf804334f5  tensorflow_io-0.19.0-cp36-cp36m-win_amd64.whl
e936247a81ce3ff20bf56b25b818f9f406fd93e9ca98fa2acaada6882a61f7f8  tensorflow_io-0.19.0-cp37-cp37m-macosx_10_14_x86_64.whl
1ae7ec15e8cdbd03087dc0fbc31b62a5cee3348adde380ceec1216456168e910  tensorflow_io-0.19.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
d23ee7f0dc3ecb6435c89610af8e3b70e36f3f94e28f0835638f0ee8bac44efb  tensorflow_io-0.19.0-cp37-cp37m-win_amd64.whl
666167c07c5134b45657f5b5f57867f3db3dd515dd4276db66febca2364af841  tensorflow_io-0.19.0-cp38-cp38-macosx_10_14_x86_64.whl
6ced86ffc16074ee22c20cab169c5611660b73a56553561fcc4cf482fa885ddc  tensorflow_io-0.19.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
dd603600ae1996930d4457a39414fbbfeccb3037975b01af39fa87deb030b118  tensorflow_io-0.19.0-cp38-cp38-win_amd64.whl
84bf6dc6ead54aa048051e400952f16324eab96db2fbfac40956d27f305dff5c  tensorflow_io-0.19.0-cp39-cp39-macosx_10_14_x86_64.whl
8645f70b7d4b4fdb6e0d851d35f66fc9cee5f04f9d6822f2373181741294efd8  tensorflow_io-0.19.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
f284a5b45b2e1fcf5f80d15bf74d37a34ecc8098c546818a27219bd134cae961  tensorflow_io-0.19.0-cp39-cp39-win_amd64.whl
f75bed42e661c7c7815629314918a5ee189d4a4ecab4a163be9e9a991aadef67  tensorflow_io_gcs_filesystem-0.19.0-cp36-cp36m-macosx_10_14_x86_64.whl
f6c055d2e49af5e387ec9d9ff408343a52cbfd9158b553acc58ad082e1cb8f93  tensorflow_io_gcs_filesystem-0.19.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
40a17de5e1e1f72564b0b2dbcc661b30c09c6f30bfb722ef331fd8d03fa9e31c  tensorflow_io_gcs_filesystem-0.19.0-cp36-cp36m-win_amd64.whl
89e5296775c8f02c244f09f3f105eae36123c825ada88822196c9fd50a711583  tensorflow_io_gcs_filesystem-0.19.0-cp37-cp37m-macosx_10_14_x86_64.whl
8862604ce96aa664e0fba939e3d7f4b920567c871fa2f4aad112e1cf40866498  tensorflow_io_gcs_filesystem-0.19.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
515368da8ef7ae4c158ff0fab4857d831634426d0174a764bd228c8de12ff349  tensorflow_io_gcs_filesystem-0.19.0-cp37-cp37m-win_amd64.whl
eb3a7b2861f0d090880d10a6ff5a44f5da538089bcc3a2e66f69aca5d9d6ec70  tensorflow_io_gcs_filesystem-0.19.0-cp38-cp38-macosx_10_14_x86_64.whl
d5cc65aec979a6329a360d8e6d10c13f13cac404892bb6df797080f406e6be51  tensorflow_io_gcs_filesystem-0.19.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
e6990a3063dac3e2ca177986d6d43d1c6ada67f4fd52bcf36bb5249d895460c5  tensorflow_io_gcs_filesystem-0.19.0-cp38-cp38-win_amd64.whl
6c543fe3250cf368e32abcc8066276acb4baad9c2f9fddbb312c99ecaf787c40  tensorflow_io_gcs_filesystem-0.19.0-cp39-cp39-macosx_10_14_x86_64.whl
f0a851d82f356f50ef4423ac9a3a510193c981f97a039031fe8aff0deae42a46  tensorflow_io_gcs_filesystem-0.19.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
1135f64e57e69dc5d290869fb7183406239dce194c311edb1f2a84af9fec0d35  tensorflow_io_gcs_filesystem-0.19.0-cp39-cp39-win_amd64.whl
```

**Comment by yongtang** [comment]
Will update and push the release on 06/25, if no surprises in between now and then.

**Comment by yongtang** [comment]
0.19.0 has been released:

https://pypi.org/project/tensorflow-io/0.19.0/

https://pypi.org/project/tensorflow-io-gcs-filesystem/0.19.0/

https://github.com/tensorflow/io/releases/tag/v0.19.0

Thanks all for the help and support!

**Comment by kvignesh1420** [comment]
Thanks @yongtang !!

**Comment by kvignesh1420** [comment]
@yongtang I think this can be closed in favour of https://github.com/tensorflow/io/issues/1474
