### ISSUE TITLE
tensorflow-io 0.22.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1555]
With TensorFlow 2.7 release, we will work on a v0.22.0 release.

Here is the list of items for 0.22.0:

- [x] Bump version string to 0.22.0 in tensorflow_io/python/ops/version_ops.py (PR #1556)
- [x] Update RELEASE.md to capture 0.22.0 changes  (PR #1556)
- [x] Update README.md to update 0.22.0 release date  (PR #1556)
- [x]  When GitHub Actions complete the build against the master, download the artifact with the name tensorflow-io-release. Uncompress the content and all binaries for release are inside.
- [x] Do minimal sanity test to make sure at least the first section of getting started example code works locally.
- [x] Ideally, push to https://test.pypi.org for additional sanity test.
- [x] Push all binaries to PyPI.org.
- [x] Release on GitHub repo with v0.22.0 tag.

/cc @vlasenkoalexey @terrytangyuan @kvignesh1420 @burgerkingeater @BryanCutler @dmitrievanthony

**Comment by yongtang** [comment]
The candidate binary can be downloaded through https://github.com/tensorflow/io/actions/runs/1442987394 (under the download button pointing to `tensorflow-io-release | 206 MB`).

@kvignesh1420 My internet is quite slow. Wondering if you can help download the binary locally and then push to PyPI.org?

**Comment by yongtang** [comment]
The candidate binary can be downloaded through https://github.com/tensorflow/io/actions/runs/1442987394 (under the download button pointing to `tensorflow-io-release | 206 MB`).

@kvignesh1420 My internet is quite slow. Wondering if you can help download the binary locally and then push to PyPI.org?

**Comment by yongtang** [comment]
The candidate binary can be downloaded through https://github.com/tensorflow/io/actions/runs/1442987394 (under the download button pointing to `tensorflow-io-release | 206 MB`).

@kvignesh1420 My internet is quite slow. Wondering if you can help download the binary locally and then push to PyPI.org?

**Comment by yongtang** [comment]
Binaries:
```sh
tensorflow-io-release % shasum -a 256 *.whl
df8983d849674a27d70a2561b8f6571a704ac212e1df0c49c283eddf471e3f6c  tensorflow_io-0.22.0-cp37-cp37m-macosx_10_14_x86_64.whl
01fec275636a39a9fe14baa1aecd66140a5729f4a2c34fba6a828dce70c718a5  tensorflow_io-0.22.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
755c9a79cf0e716ec101e07c93accff8bb5f338cbb591ab45f145d3cf4329134  tensorflow_io-0.22.0-cp37-cp37m-win_amd64.whl
c3e9a32f337e667964f38e8cc32f03748842995715220401b5c20e1105f1d306  tensorflow_io-0.22.0-cp38-cp38-macosx_10_14_x86_64.whl
78814229a20d4623f0d23d25d8cabf431b7b72b8f1ef506aa19314c460d28f50  tensorflow_io-0.22.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
c1c7a1b4f803d374b501b87582c00d3faa669be27a1d91e55dd86ce52da0192f  tensorflow_io-0.22.0-cp38-cp38-win_amd64.whl
9805a859c974e11f166297a2a5467581476fdc402d26a1c142dd1148255eadf7  tensorflow_io-0.22.0-cp39-cp39-macosx_10_14_x86_64.whl
e3ed0662c8cfd932976e64b61541e6883484dc3d9c77bc4d005ac0705f3635df  tensorflow_io-0.22.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
bc8804a7cfd04409c775a2297b3f11255dd15fb84646fef5e40507b909b20ee3  tensorflow_io-0.22.0-cp39-cp39-win_amd64.whl
c5de3d42baf0bf0c7fad173dcae2e93b79176f701b1083f28fa698bd507785ec  tensorflow_io_gcs_filesystem-0.22.0-cp37-cp37m-macosx_10_14_x86_64.whl
32b9f368486ffd748801e3d8602de1868334406ef47d63292f7fceee1f491d4d  tensorflow_io_gcs_filesystem-0.22.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
ff734f70c80709263b633839f29edc15669f13fa213084ce4e85a3d0215ca7fd  tensorflow_io_gcs_filesystem-0.22.0-cp37-cp37m-win_amd64.whl
14b80d87c3876a1915d5b45ee46291c82f577113de88a852fa5918f0ac1ba949  tensorflow_io_gcs_filesystem-0.22.0-cp38-cp38-macosx_10_14_x86_64.whl
def85b562e53d540c8ed620780b3a7f6c925a69bc4534014c29100bd4a014f9c  tensorflow_io_gcs_filesystem-0.22.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
4345771944f1bbc4bd38ed35de9248b8cec10af78ce107c96f0a45bd20b152d5  tensorflow_io_gcs_filesystem-0.22.0-cp38-cp38-win_amd64.whl
a4d2a30c3fb966f8d74ec41380ab2a101dad46aa73a3f0e9f8e5b1dee6bc4cf7  tensorflow_io_gcs_filesystem-0.22.0-cp39-cp39-macosx_10_14_x86_64.whl
fd002b7eb9d0e4d7c188825ce3f73be5a63c19eac67ef3441f5448d3b024405b  tensorflow_io_gcs_filesystem-0.22.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
ab3967679a360650609fef533c1fe9157f83264a542584a95407329b45dfd514  tensorflow_io_gcs_filesystem-0.22.0-cp39-cp39-win_amd64.whl
```

**Comment by yongtang** [comment]
Release is available now:

https://pypi.org/project/tensorflow-io/0.22.0/
https://pypi.org/project/tensorflow-io-gcs-filesystem/0.22.0/

https://github.com/tensorflow/io/releases/tag/v0.22.0

**Comment by kvignesh1420** [comment]
> The candidate binary can be downloaded through https://github.com/tensorflow/io/actions/runs/1442987394 (under the download button pointing to `tensorflow-io-release | 206 MB`).
> 
> @kvignesh1420 My internet is quite slow. Wondering if you can help download the binary locally and then push to PyPI.org?

@yongtang sorry just saw your comment. Thanks for releasing!

**Comment by yongtang** [comment]
@kvignesh1420 Thanks for the PR to bring TF 2.7 support!
