### ISSUE TITLE
tensorflow-io 0.2.0 release

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#57]
This issue tracks the efforts to release tensorflow-io 0.2.0.

Since TensorFlow 1.13 has not been released, tensorflow-io 0.2.0 will be based on TensorFlow 1.12.

- [x] Update `README.md` to add additional supported ops since 0.1.0 (@BryanCutler)
- [x] Update `README.md` to add link to individual ops' README.md if possible.  (@BryanCutler)
- [x] Change setup.py to fix `tensorflow==1.12.0`, as `1.13` is not compatible. (#65/@yongtang)
- [x] Add integration test in `tests` so that the build of `*.whl` files work correctly (#64/@yongtang)
- [x] Add examples in `doc/tutorials` so that end user could see the use case (defer to tensorflow 1.13).
- [x] Update R-packages so that additional ops are supported. (#70/ @terrytangyuan)
- [x] Update `RELEASE.md` to capture 0.2.0 changes (#66 / @yongtang)
- [x] Build `*.whl` files and push to PyPI.org  (@BryanCutler)
- [x] Release R packages to CRAN.

If you want to help, you can add a comment to indicate the items you are working on.

**Comment by BryanCutler** [comment]
I could take the first 2 `README.md` updates, and `Build/push `*.whl` files`

> Add examples in doc/tutorials so that end user could see the use case
what kind of format will we make these tutorials, markdowns files also in the github repo or is it possible to have sphinx/html, or something?

**Comment by yongtang** [comment]
Thanks @BryanCutler! I think markdown files with sample code would be a good start really.

**Comment by BryanCutler** [comment]
>could you create an account in PyPI.org and create a PR to add your name and PyPI.org handle to Current Release Team

Done, PR https://github.com/tensorflow/community/pull/59

**Comment by yongtang** [comment]
I think we cover all items. The `doc/tutorials` probably could be deferred to the next release as with tensorflow 1.13 it is possible to combine `tf.data` with `tf.keras` and the examples will be more telling. With 1.12 there are still many bugs for tf.data to work with higher level apis.

**Comment by yongtang** [comment]
Just tased v0.2.0. @BryanCutler Would you like to help build the *.whl files and push to PyPI.org?

The build method for *.whl files have been updated, see PR   tensorflow/community#58
```
$ docker run -it -e BAZEL_VERSION=0.20.0 --rm -v ${PWD}:/working_dir \
    -w /working_dir  tensorflow/tensorflow:custom-op \
    bash -x /working_dir/.travis/python.release.sh <2.7|3.4|3.5|3.6>
```

Once 4 *.whl files are generated, you could push it to PyPI.org

**Comment by terrytangyuan** [comment]
We might want to consider setting up automatic PyPI release on Travis going forward so whenever a release tag is made, Travis builds and pushes artifacts to PyPI: 
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by BryanCutler** [comment]
> @BryanCutler Would you like to help build the *.whl files and push to PyPI.org?

Sure I will do it now, thanks!

**Comment by BryanCutler** [comment]
The wheels have been uploaded, yay!  I ran a quick local test before publishing and will also try to install from PyPI. Nice work everyone!!

**Comment by terrytangyuan** [comment]
Great work everyone! I am closing this issue now. The last item - "Release R packages to CRAN" - will be tracked separately in https://github.com/tensorflow/io/issues/18

**Comment by yongtang** [comment]
Thanks all for great work!
